### ISSUE TITLE
Problems when i try to run a single LSTM for audio and face 

### ISSUE THREAD

**Issue by mijailronald23** [jimmy-ren/lstm_speaker_naming_aaai16#2]
Hi all, 

Nice paper, i tried to reproduce your results. I downloaded the code and data but when i tried to run in mi computer, i have this message:

> > > > test_audio_all

Undefined function 'to_gpu' for input arguments of type 'double'.
Error in sn_audio_init (line 45)
 config.weights.Whg{1} = config.NEW_MEM(rand(config.hidden_layer_size(1),config.hidden_layer_size(1))_2_r-r);

Error in test_audio_all (line 7)
sn_audio_init();

and the same thing happens when i did for face data
can you help me with that?  please

**Comment by jimmy-ren** [comment]
Go to the LSTM_sn_audio_only folder and run the code.

**Comment by mijailronald23** [comment]
My mistake, the code works very well, thanks for the support
